<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users Registry Printout</title>
    <!-- Simple Print Styling -->
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 30px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        h2 {
            margin: 0;
            text-transform: uppercase;
        }
        .meta {
            font-size: 12px;
            color: #666;
            margin-top: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
            font-size: 13px;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .status-active {
            color: green;
            font-weight: bold;
        }
        .status-suspended {
            color: red;
            font-weight: bold;
        }
        @media print {
            .no-print {
                display: none;
            }
            body {
                margin: 0;
            }
        }
    </style>
</head>
<body>

    <div class="header">
        <h2>Mobile ERP - Users Registry</h2>
        <div class="meta">Generated by: {{ auth()->user()->name }} | Date: {{ now()->format('d M Y, h:i A') }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th width="50">ID</th>
                <th>Full Name</th>
                <th>Username</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Branch</th>
                <th>Assigned Role</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
            <tr>
                <td>{{ $user->id }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->username ?? 'N/A' }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->phone ?? 'N/A' }}</td>
                <td>{{ $user->branch->name ?? 'N/A' }}</td>
                <td>{{ $user->roles->first()?->display_name ?? 'N/A' }}</td>
                <td>
                    @if($user->status)
                        <span class="status-active">Active</span>
                    @else
                        <span class="status-suspended">Suspended</span>
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <script>
        window.onload = function() {
            window.print();
        }
    </script>
</body>
</html>
